Include(FetchContent)

set(CUTLASS_ENABLE_EXAMPLES_INIT OFF)
set(CUTLASS_ENABLE_TOOLS_INIT OFF)
set(CUTLASS_ENABLE_LIBRARY_INIT OFF)
set(CUTLASS_ENABLE_LIBRARY OFF)
set(CUTLASS_ENABLE_PROFILER OFF)
set(CUTLASS_ENABLE_TESTS_INIT OFF)
set(CUTLASS_ENABLE_EXAMPLES OFF)
set (CUTLASS_ENABLE_HEADERS_ONLY ON)
FetchContent_Declare(
  cutlass
  GIT_REPOSITORY https://github.com/NVIDIA/cutlass.git
  GIT_TAG        v3.5.1
)
FetchContent_MakeAvailable(cutlass)
